version: 2.1

orbs:
  automation: willian-gama/android-ci@dev:chore/split-tests

parameters:
  action:
    description: action type to execute workflow
    type: enum
    enum: [build, firebase]
    default: build

workflows:
  build_and_test:
    when:
      equal: [ build, << pipeline.parameters.action >> ]
    jobs:
      - automation/android_setup:
          build_variant: debug
      - automation/unit_tests:
          build_variant: debug
          parallelism: 3
          requires:
            - automation/android_setup
      - automation/screenshot_tests:
          build_variant: debug
          parallelism: 3
          requires:
            - automation/android_setup
      - automation/ui_tests:
          build_variant: debug
          parallelism: 3
          requires:
            - automation/android_setup
      - automation/code_linting:
          build_variant: debug
          requires:
            - automation/android_setup
      - automation/code_coverage:
          requires:
            - automation/unit_tests
            - automation/ui_tests

  release-firebase-build:
    when:
      equal: [ firebase, << pipeline.parameters.action >> ]
    jobs:
      - automation/android_setup:
          build_variant: debug
      - automation/firebase_app_distribution:
          requires:
            - automation/android_setup