version: '2.1'
orbs:
  automation: willian-gama/android-orb@1.0.31
workflows:
  build_and_test:
    jobs:
      - automation/android_setup
      - automation/unit_tests:
          build_variant: debug
          run_screenshot_tests: true
          requires:
            - automation/android_setup
      - automation/ui_tests:
          build_variant: debug
          requires:
            - automation/android_setup
      - automation/code_linting:
          build_variant: debug
          requires:
            - automation/android_setup
      - automation/code_coverage:
          requires:
            - automation/unit_tests
            - automation/ui_tests