name: android_ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" , "main" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  API_KEY: ${{ secrets.API_KEY }}
  GPR_USERNAME: ${{ secrets.GPR_USERNAME }}
  GPR_KEY: ${{ secrets.GPR_KEY }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  code_linting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project sources
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@b5418f5a58f5fd2eb486dd7efb368fe7be7eae45 # v2

      - name: set up jdk 20
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: 'zulu' # Supported distributions: https://github.com/actions/setup-java#supported-distributions
          java-version: '20'

      - name: setup gradle
        uses: gradle/gradle-build-action@bdf99f9dada2506e990bac6de8ec5e3de34a04f1 # v3

      - name: create local.properties from secret variables
        run: scripts/generate_local_properties.sh

      # KtLint
      - name: run ktlintCheck
        run: ./gradlew ktlintCheck

      - name: archive ktLint reports on failure
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        if: failure()
        with:
          name: code_linting
          path: "**/build/reports/ktlint/**/*.html"

      # Detekt
      - name: run detekt
        run: ./gradlew detekt
        if: success() || failure()

      - name: archive detekt reports on failure
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        if: failure()
        with:
          name: code_linting
          path: "**/build/reports/detekt/*.html"

  unit_tests:
    needs: code_linting
    runs-on: ubuntu-latest
    steps:
      - name: checkout project sources
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@b5418f5a58f5fd2eb486dd7efb368fe7be7eae45 # v2

      - name: set up jdk 20
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: 'zulu'
          java-version: '20'

      - name: setup gradle
        uses: gradle/gradle-build-action@bdf99f9dada2506e990bac6de8ec5e3de34a04f1 # v3

      - name: create local.properties from secret variables
        run: scripts/generate_local_properties.sh

      # Run unit tests: https://developer.android.com/studio/test/command-line#run-tests-build-variants
      - name: run unit tests
        run: ./gradlew testDebugUnitTest

      - name: archive unit tests on failure
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        if: failure()
        with:
          name: unit_tests
          path: "**/build/reports/tests/testDebugUnitTest"

  screenshot_tests:
    needs: code_linting
    runs-on: ubuntu-latest
    steps:
      - name: checkout project sources
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@b5418f5a58f5fd2eb486dd7efb368fe7be7eae45 # v2

      - name: set up jdk 20
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: 'zulu'
          java-version: '20'

      - name: setup gradle
        uses: gradle/gradle-build-action@bdf99f9dada2506e990bac6de8ec5e3de34a04f1 # v3

      - name: create local.properties from secret variables
        run: scripts/generate_local_properties.sh

      # Run unit tests: https://developer.android.com/studio/test/command-line#run-tests-build-variants
      - name: run screenshot tests
        run: ./gradlew verifyPaparazziDebug

      - name: archive unit tests on failure
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        if: failure()
        with:
          name: unit_tests
          path: "**/build/reports/paparazzi"

  ui_tests:
    needs: code_linting
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        api-level: [ 26, 28 ]
    steps:
      - name: checkout project sources
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@b5418f5a58f5fd2eb486dd7efb368fe7be7eae45 # v2

      - name: set up jdk 20
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: 'zulu'
          java-version: '20'

      - name: create local.properties from secret variables
        run: scripts/generate_local_properties.sh

      - name: setup gradle
        uses: gradle/gradle-build-action@bdf99f9dada2506e990bac6de8ec5e3de34a04f1 # v3

      - name: avd cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create avd and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@6b0df4b0efb23bb0ec63d881db79aefbc976e4b2 # v2
        with:
          api-level: ${{ matrix.api-level }}
          script: echo "generated avd snapshot for caching."

      - name: run ui tests
        uses: reactivecircus/android-emulator-runner@6b0df4b0efb23bb0ec63d881db79aefbc976e4b2 # v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -wipe-data # Emulator options reference: https://developer.android.com/studio/run/emulator-commandline
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest # Run ui tests: https://developer.android.com/studio/test/command-line#run-tests-build-variants

      - name: archive ui test reports on failure
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        if: failure()
        with:
          name: ui_tests
          path: "**/build/reports/androidTests/connected"